# Generated by Django 6.0 on 2026-02-03 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredienteBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('Fruta', 'Fruta'), ('Verdura', 'Verdura'), ('Carniceria', 'Carnicería'), ('Pescaderia', 'Pescadería'), ('Lacteos', 'Lácteos'), ('Despensa', 'Despensa'), ('Huevos', 'Huevos'), ('Otros', 'Otros')], default='Otros', max_length=20)),
                ('calorias', models.IntegerField(default=0)),
                ('proteinas', models.FloatField(default=0.0)),
                ('grasas', models.FloatField(default=0.0)),
                ('hidratos', models.FloatField(default=0.0)),
                ('dias_caducidad', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tiempo_preparacion', models.IntegerField()),
                ('es_apta_sarten', models.BooleanField(default=False)),
                ('es_apta_airfryer', models.BooleanField(default=False)),
                ('es_apta_horno', models.BooleanField(default=False)),
                ('es_apta_microondas', models.BooleanField(default=False)),
                ('es_apta_tupper', models.BooleanField(default=True)),
                ('calorias', models.IntegerField(default=0)),
                ('proteinas', models.FloatField(default=0.0)),
                ('grasas', models.FloatField(default=0.0)),
                ('hidratos', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color_brand', models.CharField(default='#000000', help_text='Color hexadecimal para la UI', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='PlanSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('lista_compra_snapshot', models.TextField(blank=True, null=True)),
                ('coste_total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComidaPlanificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('momento', models.CharField(choices=[('COMIDA', 'Comida'), ('CENA', 'Cena')], max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='core.plansemanal')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receta')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_gramos', models.IntegerField()),
                ('ingrediente_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredientebase')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='core.receta')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=200)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peso_gramos', models.IntegerField(default=1000, help_text='Peso neto normalizado')),
                ('precio_por_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tipo_unidad_original', models.CharField(default='KG', max_length=10)),
                ('precio_referencia_original', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('ingrediente_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_disponibles', to='core.ingredientebase')),
                ('supermercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supermercado')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(default=30)),
                ('peso_kg', models.FloatField(default=70.0)),
                ('altura_cm', models.IntegerField(default=170)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=10)),
                ('objetivo', models.CharField(choices=[('PERDER', 'Perder Peso'), ('GANAR', 'Ganar Músculo'), ('MANTENER', 'Mantener Peso')], default='MANTENER', max_length=10)),
                ('nivel_actividad', models.CharField(choices=[('SEDENTARIO', 'Sedentario (Oficina, poco ejercicio)'), ('LIGERO', 'Ligero (1-3 días/sem)'), ('MODERADO', 'Moderado (3-5 días/sem)'), ('ALTO', 'Alto (6-7 días/sem)')], default='SEDENTARIO', max_length=10)),
                ('gasto_energetico_diario', models.IntegerField(default=2000)),
                ('objetivo_proteinas', models.IntegerField(default=0)),
                ('objetivo_grasas', models.IntegerField(default=0)),
                ('objetivo_hidratos', models.IntegerField(default=0)),
                ('presupuesto_semanal', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('tiene_horno', models.BooleanField(default=True)),
                ('tiene_microondas', models.BooleanField(default=True)),
                ('tiene_airfryer', models.BooleanField(default=False)),
                ('tiempo_cocina_diario', models.IntegerField(default=30)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('supermercados_seleccionados', models.ManyToManyField(blank=True, related_name='usuarios', to='core.supermercado')),
            ],
        ),
        migrations.CreateModel(
            name='CostePorSupermercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coste', models.DecimalField(decimal_places=2, max_digits=6)),
                ('es_posible', models.BooleanField(default=True, help_text='False si el súper no tiene todos los ingredientes')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costes_por_supermercado', to='core.receta')),
                ('supermercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supermercado')),
            ],
            options={
                'unique_together': {('receta', 'supermercado')},
            },
        ),
    ]
