# Generated by Django 6.0 on 2025-12-17 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredienteBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('Verdura', 'Verdura'), ('Fruta', 'Fruta'), ('Carniceria', 'Carnicería'), ('Pescaderia', 'Pescadería'), ('Lacteos', 'Lácteos'), ('Despensa', 'Despensa'), ('Panaderia', 'Panadería'), ('Huevos', 'Huevos'), ('Conservas', 'Conservas'), ('Otros', 'Otros')], default='Otros', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('instrucciones', models.TextField()),
                ('tiempo_preparacion', models.IntegerField(help_text='Tiempo en minutos')),
                ('es_apta_airfryer', models.BooleanField(default=False)),
                ('es_apta_microondas', models.BooleanField(default=False)),
                ('es_apta_horno', models.BooleanField(default=False)),
                ('es_apta_sarten', models.BooleanField(default=False)),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dominio_web', models.CharField(blank=True, max_length=100)),
                ('color_hex', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto_semanal', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('tiene_airfryer', models.BooleanField(default=False)),
                ('tiene_microondas', models.BooleanField(default=True)),
                ('tiene_horno', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_gramos', models.IntegerField()),
                ('ingrediente_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredientebase')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='core.receta')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=200)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_por_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('peso_gramos', models.IntegerField(default=0)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('nutriscore', models.CharField(blank=True, max_length=1, null=True)),
                ('ingrediente_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_disponibles', to='core.ingredientebase')),
                ('supermercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supermercado')),
            ],
        ),
    ]
