# Generated by Django 6.0 on 2025-12-22 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredienteBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('Fruta', 'Fruta'), ('Verdura', 'Verdura'), ('Carniceria', 'Carnicería'), ('Pescaderia', 'Pescadería'), ('Lacteos', 'Lácteos'), ('Despensa', 'Despensa'), ('Huevos', 'Huevos'), ('Otros', 'Otros')], default='Otros', max_length=20)),
                ('calorias', models.IntegerField(default=0, help_text='Kcal por 100g')),
                ('proteinas', models.FloatField(default=0.0)),
                ('grasas', models.FloatField(default=0.0)),
                ('hidratos', models.FloatField(default=0.0)),
                ('dias_caducidad', models.IntegerField(default=7, help_text='Días aprox antes de caducar')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tiempo_preparacion', models.IntegerField(help_text='Minutos')),
                ('es_apta_sarten', models.BooleanField(default=False)),
                ('es_apta_airfryer', models.BooleanField(default=False)),
                ('es_apta_horno', models.BooleanField(default=False)),
                ('es_apta_microondas', models.BooleanField(default=False)),
                ('es_apta_tupper', models.BooleanField(default=True)),
                ('precio_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(default=30)),
                ('peso_kg', models.FloatField(default=70.0)),
                ('altura_cm', models.IntegerField(default=170)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=10)),
                ('objetivo', models.CharField(choices=[('PERDER', 'Perder Peso'), ('GANAR', 'Ganar Músculo'), ('MANTENER', 'Mantener Peso')], default='MANTENER', max_length=10)),
                ('nivel_actividad', models.CharField(choices=[('SEDENTARIO', 'Sedentario (Oficina, poco ejercicio)'), ('LIGERO', 'Ligero (1-3 días/sem)'), ('MODERADO', 'Moderado (3-5 días/sem)'), ('ALTO', 'Alto (6-7 días/sem)')], default='SEDENTARIO', max_length=10)),
                ('gasto_energetico_diario', models.IntegerField(default=2000, help_text='Calorías diarias recomendadas')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('lista_compra_generada', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComidaPlanificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('momento', models.CharField(choices=[('COMIDA', 'Comida'), ('CENA', 'Cena')], max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='core.plansemanal')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receta')),
            ],
            options={
                'ordering': ['dia_semana', 'momento'],
            },
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_gramos', models.IntegerField()),
                ('ingrediente_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredientebase')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='core.receta')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=200)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo_unidad', models.CharField(choices=[('KG', 'Kilogramos (Granel/Malla)'), ('L', 'Litros (Botellas/Bricks)'), ('UD', 'Unidades (Huevos, Yogures, Piezas)')], default='KG', max_length=2)),
                ('cantidad_pack', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('precio_por_unidad_medida', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('peso_gramos', models.IntegerField(default=0, help_text='Peso neto TOTAL calculado en gramos')),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ingrediente_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_disponibles', to='core.ingredientebase')),
                ('supermercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supermercado')),
            ],
        ),
    ]
