# Generated by Django 6.0 on 2025-12-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='presupuesto_semanal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tiempo_cocina_diario',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tiempo_cocina_finde',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tiene_airfryer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tiene_horno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tiene_microondas',
            field=models.BooleanField(default=True),
        ),
    ]
