# Generated by Django 6.0 on 2025-12-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilusuario_presupuesto_semanal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='objetivo_grasas',
            field=models.IntegerField(default=0, help_text='Gramos diarios'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='objetivo_hidratos',
            field=models.IntegerField(default=0, help_text='Gramos diarios'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='objetivo_proteinas',
            field=models.IntegerField(default=0, help_text='Gramos diarios'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='gasto_energetico_diario',
            field=models.IntegerField(default=2000, help_text='Calorías diarias (TDEE)'),
        ),
    ]
