# Generated by Django 6.0 on 2025-12-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilusuario_objetivo_grasas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='calorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receta',
            name='grasas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='receta',
            name='hidratos',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='receta',
            name='proteinas',
            field=models.FloatField(default=0.0),
        ),
    ]
